// Generated by cbindgen from mobile/anki-ffi. Do not edit by hand.

#ifndef ANKI_FFI_H
#define ANKI_FFI_H

#pragma once

// WARNING: this file is auto-generated; edits will be lost.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct AnkiBackend AnkiBackend;


#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns a pointer to a NUL-terminated string describing the most recent
 * error on the *current thread*, or null if there is none.
 *
 * The returned pointer is owned by this crate's thread-local storage and is
 * valid until the next FFI call on the same thread. Callers must copy the
 * string if they need to retain it; they must NOT free it.
 *
 * # Safety
 *
 * The caller must not retain the pointer across subsequent FFI calls on the
 * same thread.
 */
const char *anki_last_error(void);

/**
 * Decodes an `anki.backend.BackendInit` protobuf and opens a backend.
 *
 * On success, returns an owned, non-null `*mut Backend` that must be released
 * with [`anki_close_backend`]. On failure, returns null and records a message
 * retrievable via [`anki_last_error`].
 *
 * # Safety
 *
 * `init_ptr` must either be null (treated as an empty `BackendInit`) or point
 * to at least `len` readable bytes.
 */
AnkiBackend *anki_open_backend(const uint8_t *init_ptr, uintptr_t len);

/**
 * Runs a backend service method, mirroring `rsbridge`'s `command`.
 *
 * On success writes `*status = 0` and returns a heap buffer holding the
 * encoded protobuf response. On a backend error writes `*status = 1` and
 * returns a heap buffer holding the encoded `anki.backend.BackendError`. On a
 * usage error (e.g. null backend) writes `*status = -1`, records a message in
 * [`anki_last_error`], and returns null.
 *
 * In all non-null return cases `*out_len` is set to the buffer length and the
 * caller must release the buffer with [`anki_free`] using that same length.
 *
 * Blocks the calling thread; see the module-level threading note.
 *
 * # Safety
 *
 * `be` must be a pointer returned by [`anki_open_backend`] that has not been
 * closed. `in_ptr` must be null or valid for `in_len` bytes. `out_len` and
 * `status` must be valid, writable pointers.
 */
uint8_t *anki_command(AnkiBackend *be,
                      uint32_t service,
                      uint32_t method,
                      const uint8_t *in_ptr,
                      uintptr_t in_len,
                      uintptr_t *out_len,
                      int32_t *status);

/**
 * Releases a buffer previously returned by [`anki_command`].
 *
 * # Safety
 *
 * `ptr`/`len` must be exactly the pointer and length produced by a single
 * [`anki_command`] call, and must not be freed more than once. A null `ptr`
 * (the empty-response case) is a no-op.
 */
void anki_free(uint8_t *ptr, uintptr_t len);

/**
 * Closes a backend previously opened by [`anki_open_backend`].
 *
 * # Safety
 *
 * `be` must be a pointer returned by [`anki_open_backend`] that has not
 * already been closed. A null pointer is a no-op.
 */
void anki_close_backend(AnkiBackend *be);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ANKI_FFI_H */
